name: Build, Test and SonarCloud Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build, Test and SonarCloud Analysis
    runs-on: ubuntu-latest
    env:
      MAILERSEND_TOKEN: ${{ secrets.MAILERSEND_TOKEN }}
      MAILERSEND_BASE_URL: ${{ secrets.MAILERSEND_BASE_URL }}
      MAILERSEND_TEMPLATE: ${{ secrets.MAILERSEND_TEMPLATE }}
      PORT: 8080
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build

      - name: Run SonarCloud Analysis
        run: ./gradlew sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=DietiEstates25_backend \
          -Dsonar.login=$SONAR_TOKEN