name: SonarCloud analysis

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: AntonioTagliafierro_INGSW_24-25-DietiEstates25-server
          organization: antoniotagliafierro
          projectBaseDir: .
          args: >
            -Dsonar.sources=src/main/kotlin
            -Dsonar.tests=src/test/kotlin
            -Dsonar.exclusions=**/.env,**/secrets/**
            -Dsonar.kotlin.detekt.reportPaths=build/reports/detekt/detekt.xml
            -Dsonar.verbose=true
